DROP DATABASE IF EXISTS task3;
CREATE DATABASE task3;
USE task3;

DROP TABLE IF EXISTS ART;
DROP TABLE IF EXISTS ARTIST;
DROP TABLE IF EXISTS ART_PUBLISHER;
DROP TABLE IF EXISTS ORDER_;

CREATE TABLE ART (
	Art_id INT NOT NULL,
    Style VARCHAR(50),
    Location VARCHAR(50),
    Publisher VARCHAR(50) NOT NULL,
    PRIMARY KEY (Art_id),
    FOREIGN KEY(Publisher) REFERENCES ART_PUBLISHER(Name_) ON DELETE CASCADE
);

CREATE TABLE ARTIST (
	Art_id INT NOT NULL,
    Artist_name VARCHAR(50) NOT NULL,
    PRIMARY KEY(Artist_name),
    FOREIGN KEY(Art_id) REFERENCES ART(Art_id) ON DELETE CASCADE
);

CREATE TABLE ART_PUBLISHER (
	Name_ VARCHAR(50) NOT NULL,
    Address VARCHAR(100),
    telephone VARCHAR(15),
    PRIMARY KEY(Name_)
);

CREATE TABLE ORDER_ (
	Art_id INT NOT NULL,
    Order_id INT NOT NULL,
    Date_ DATE,
    Price DECIMAL(10,2),
    PRIMARY KEY(Order_id),
    FOREIGN KEY(Art_id) REFERENCES ART(Art_id) ON DELETE CASCADE
);